// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddnewtableCashCountPeriodChangeandaddnewfieldtotableCashCountAction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddnewtableCashCountPeriodChangeandaddnewfieldtotableCashCountAction));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191953571_Add new table - CashCountPeriodChange and add new field to table CashCountAction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
