//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalAccounting.ProgramService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProgramService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginAndPasswordVerification", ReplyAction="http://tempuri.org/IService/LoginAndPasswordVerificationResponse")]
        bool LoginAndPasswordVerification(string login, string password, string repeatpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginAndPasswordVerification", ReplyAction="http://tempuri.org/IService/LoginAndPasswordVerificationResponse")]
        System.Threading.Tasks.Task<bool> LoginAndPasswordVerificationAsync(string login, string password, string repeatpassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PersonalAccounting.ProgramService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PersonalAccounting.ProgramService.IService>, PersonalAccounting.ProgramService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LoginAndPasswordVerification(string login, string password, string repeatpassword) {
            return base.Channel.LoginAndPasswordVerification(login, password, repeatpassword);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAndPasswordVerificationAsync(string login, string password, string repeatpassword) {
            return base.Channel.LoginAndPasswordVerificationAsync(login, password, repeatpassword);
        }
    }
}
